apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: if-demo
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:slaudi/informatica_25.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

